version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo Logging in to Amazon S3...
      - aws s3 cp templates/ s3://$TEMPLATE_BUCKET/templates/ --recursive
  build:
    commands:
      - echo Build started on `date`
      - echo Checking stack status...
      - |
        STACK_STATUS=$(aws cloudformation describe-stacks --stack-name web-infrastructure-$ENVIRONMENT --query 'Stacks[0].StackStatus' --output text 2>/dev/null || echo "DOES_NOT_EXIST")
        if [ "$STACK_STATUS" = "ROLLBACK_COMPLETE" ]; then
          echo "Stack is in ROLLBACK_COMPLETE state, deleting..."
          aws cloudformation delete-stack --stack-name web-infrastructure-$ENVIRONMENT
          aws cloudformation wait stack-delete-complete --stack-name web-infrastructure-$ENVIRONMENT
        fi
      - echo Deploying CloudFormation stack...
      - |
        if aws cloudformation deploy \
          --template-file main.yaml \
          --stack-name web-infrastructure-$ENVIRONMENT \
          --parameter-overrides Environment=$ENVIRONMENT \
          --capabilities CAPABILITY_IAM \
          --no-fail-on-empty-changeset; then
          echo "Deployment successful"
        else
          echo "Deployment failed, initiating automatic rollback..."
          aws cloudformation describe-stack-events \
            --stack-name web-infrastructure-$ENVIRONMENT \
            --query 'StackEvents[?ResourceStatus==`CREATE_FAILED` || ResourceStatus==`UPDATE_FAILED`].[LogicalResourceId,ResourceStatusReason]' \
            --output table
          
          echo "Starting rollback process..."
          aws cloudformation cancel-update-stack \
            --stack-name web-infrastructure-$ENVIRONMENT 2>/dev/null || \
          aws cloudformation continue-update-rollback \
            --stack-name web-infrastructure-$ENVIRONMENT
          
          echo "Waiting for rollback to complete..."
          aws cloudformation wait stack-rollback-complete \
            --stack-name web-infrastructure-$ENVIRONMENT
          
          echo "Rollback completed, deployment failed"
          exit 1
        fi
  post_build:
    commands:
      - echo Build completed on `date`
      - aws cloudformation describe-stacks --stack-name web-infrastructure-$ENVIRONMENT --query 'Stacks[0].Outputs'