AWSTemplateFormatVersion: 2010-09-09
Description: 'Application Load Balancer and Target Group'

# ALB Access Logging Configuration:
# ALB access logs are stored in S3, not CloudWatch Logs directly.
# To enable access logging, add LoadBalancerAttributes to the ApplicationLoadBalancer resource:
#   LoadBalancerAttributes:
#     - Key: access_logs.s3.enabled
#       Value: 'true'
#     - Key: access_logs.s3.bucket
#       Value: !Sub 'web-alb-logs-${Environment}-${AWS::AccountId}'
# Note: S3 bucket must be created separately with appropriate bucket policy for ALB service.

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prod]
  VPCId:
    Type: String
  PublicSubnetId:
    Type: String
  PublicSubnet2Id:
    Type: String
  ALBSecurityGroupId:
    Type: String


Resources:
  ApplicationLoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub 'web-alb-${Environment}'
      Scheme: internet-facing
      Type: application
      Subnets:
        - !Ref PublicSubnetId
        - !Ref PublicSubnet2Id
      SecurityGroups:
        - !Ref ALBSecurityGroupId
      Tags:
        - Key: Name
          Value: !Sub 'web-alb-${Environment}'

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub 'web-tg-${Environment}'
      Port: 80
      Protocol: HTTP
      VpcId: !Ref VPCId
      HealthCheckPath: /
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3

      Tags:
        - Key: Name
          Value: !Sub 'web-tg-${Environment}'

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref ApplicationLoadBalancer
      Port: 80
      Protocol: HTTP

Outputs:
  ALBDNSName:
    Value: !GetAtt ApplicationLoadBalancer.DNSName
  TargetGroupArn:
    Value: !Ref TargetGroup
  ALBFullName:
    Description: Full name of the Application Load Balancer for CloudWatch metrics
    Value: !GetAtt ApplicationLoadBalancer.LoadBalancerFullName
  TargetGroupFullName:
    Description: Full name of the Target Group for CloudWatch metrics
    Value: !GetAtt TargetGroup.TargetGroupFullName